=== yihtserns/spom/src/test/resources/com/github/yihtserns/spom/spom.xsd
<xs:schema id="NewDataSet" targetNamespace="http://github.com/yihtserns/spom" xmlns:mstns="http://github.com/yihtserns/spom" xmlns="http://github.com/yihtserns/spom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="project">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="issueManagement" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="system" form="unqualified" type="xs:string" />
            <xs:attribute name="url" form="unqualified" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="license" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" form="unqualified" type="xs:string" />
            <xs:attribute name="url" form="unqualified" type="xs:string" />
            <xs:attribute name="distribution" form="unqualified" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="scm" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="connection" form="unqualified" type="xs:string" />
            <xs:attribute name="developerConnection" form="unqualified" type="xs:string" />
            <xs:attribute name="url" form="unqualified" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="developer" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="id" form="unqualified" type="xs:string" />
            <xs:attribute name="name" form="unqualified" type="xs:string" />
            <xs:attribute name="email" form="unqualified" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="properties" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:anyAttribute namespace="##local" processContents="skip"/>
                </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="dependencies" minOccurs="0">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="compile" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" form="unqualified" type="xs:string" />
                  <xs:attribute name="exclude" form="unqualified" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="provided" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" form="unqualified" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="runtime" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" form="unqualified" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="test" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" form="unqualified" type="xs:string" />
                  <xs:attribute name="exclude" form="unqualified" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="parent" form="unqualified" type="xs:string" />
      <xs:attribute name="id" form="unqualified" type="xs:string" use="required"/>
      <xs:attribute name="name" form="unqualified" type="xs:string" />
      <xs:attribute name="description" form="unqualified" type="xs:string" />
      <xs:attribute name="url" form="unqualified" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="project" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yihtserns/spom/src/test/resources/com/github/yihtserns/spom/spom.xml
<project xmlns="http://github.com/yihtserns/spom"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://github.com/yihtserns/spom http://github.com/yihtserns/spom/spom.xsd"
         parent="org.sonatype.oss:oss-parent:7"
         id="com.github.yihtserns:camelscript:0.0.2-SNAPSHOT@jar"
         name="Camel Script"
         description="Provides syntactic sugar for Apache Camel to make it easy to configure in Groovy script."
         url="http://github.com/yihtserns/camelscript">

    <issueManagement system="Github" url="http://github.com/yihtserns/camelscript/issues"/>
    <license name="Apache License, Version 2.0" url="http://www.apache.org/licenses/LICENSE-2.0" distribution="repo"/>
    <scm connection="scm:git:git@github.com:yihtserns/camelscript.git" developerConnection="scm:git:git@github.com:yihtserns/camelscript.git" url="git@github.com:yihtserns/camelscript.git"/>
    <developer id="yihtserns" name="Sim Yih Tsern" email="sim_yihtsern@yahoo.com"/>

    <properties project.build.sourceEncoding="UTF-8"
                hamcrest.version="1.2.1"
                groovy.version="2.2.2"
                camel.version="2.4.0"
                slf4j.version="1.6.1"
                logback.version="0.9.29"
                something="Else"/>

    <dependencies>
        <compile id="org.apache.camel:camel-core:${camel.version}"
                 exclude="commons-logging:commons-logging-api" />
        <provided id="org.codehaus.groovy:groovy:${groovy.version}" />
        <compile id="org.slf4j:slf4j-api:${slf4j.version}" />
        <runtime id="ch.qos.logback:logback-classic:0.9.29" />
        <!-- SLF4J Bridges -->
        <runtime id="org.slf4j:jcl-over-slf4j:${slf4j.version}" />
        <runtime id="org.slf4j:log4j-over-slf4j:${slf4j.version}" />
        <!-- For unit test -->
        <test id="org.hamcrest:hamcrest-core:${hamcrest.version}" />
        <test id="org.hamcrest:hamcrest-library:${hamcrest.version}" />
        <test id="com.google.guava:guava:11.0" />
        <test id="junit:junit-dep:4.10"
              exclude="org.hamcrest:hamcrest-core"/>
        <test id="org.mockito:mockito-core:1.8.5"
              exclude="org.hamcrest:hamcrest-core" />
        <test id="org.codehaus.groovy:groovy-test:${groovy.version}" />
    </dependencies>
</project>
